Metrics/LineLength:
  Max: 100

Metrics/LineLength:
  Exclude:
    - 'spec/**/**'

Style/BlockComments:
  Exclude:
    - 'spec/**/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/**'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/**'
    - 'Gemfile'
    - 'Gemfile.lock'
